@startuml
title 学生饭卡管理系统活动图

start
:学生/管理员选择登录;
if (是学生登录?) then (是)
    :输入学生账号、密码;
    :验证学生账号密码;
    if (验证通过?) then (是)
        :进入学生操作界面;
        :选择操作（查询余额、充值、消费、挂失、解挂）;
        if (查询余额?) then (是)
            :读取饭卡信息;
            :从数据库获取余额;
            :显示余额;
        else if (充值?) then (是)
            :读取饭卡信息;
            :从数据库获取当前余额;
            :输入充值金额;
            :更新数据库余额;
            :记录充值交易;
            :显示充值成功信息;
        else if (消费?) then (是)
            :读取饭卡信息;
            :从数据库获取当前余额;
            :判断余额是否足够;
            if (余额足够?) then (是)
                :扣除数据库余额;
                :记录消费交易;
                :显示消费成功信息;
            else (否)
                :显示余额不足提示;
            endif
        else if (挂失?) then (是)
            :读取饭卡信息;
            :更新数据库中挂失状态;
            :显示挂失成功信息;
        else (解挂?)
            :读取饭卡信息;
            :更新数据库中挂失状态;
            :显示解挂成功信息;
        endif
    else (否)
        :显示学生登录失败提示;
    endif
else (否)
    :输入管理员账号、密码;
    :验证管理员账号密码;
    if (验证通过?) then (是)
        :进入管理员操作界面;
        :选择管理操作（添加学生、删除学生、修改学生信息、添加饭卡、删除饭卡、修改饭卡信息、管理系统设置）;
        if (添加学生?) then (是)
            :输入学生信息及饭卡信息;
            :插入学生及饭卡信息到数据库;
            :显示添加成功信息;
        else if (删除学生?) then (是)
            :选择要删除的学生;
            :从数据库删除学生及饭卡信息;
            :显示删除成功信息;
        else if (修改学生信息?) then (是)
            :选择要修改的学生;
            :输入修改后的学生信息;
            :更新数据库中相应学生信息;
            :显示修改成功信息;
        else if (添加饭卡?) then (是)
            :选择学生;
            :输入饭卡信息;
            :插入饭卡信息到数据库;
            :显示添加成功信息;
        else if (删除饭卡?) then (是)
            :选择要删除的饭卡;
            :从数据库删除饭卡信息;
            :显示删除成功信息;
        else if (修改饭卡信息?) then (是)
            :选择要修改的饭卡;
            :输入修改后的饭卡信息;
            :更新数据库中相应饭卡信息;
            :显示修改成功信息;
        else (管理系统设置?)
            :进行系统设置操作;
            :更新数据库中相关系统设置数据;
            :显示设置成功信息;
        endif
    else (否)
        :显示管理员登录失败提示;
    endif
endif
stop

@enduml